[secrets]
# Put your ngrok URL here if you want to override the environment variable
# e.g. OLLAMA_PUBLIC_URL = "https://xxxx.ngrok-free.app/api/generate"
OLLAMA_PUBLIC_URL = "https://xxxx.ngrok-free.app/api/generate"